In [ ]:
import pandas as pd

df = pd.read_csv('messy_sales_data.csv')
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [ ]:
df.shape

(30, 9)

In [ ]:
df.dtypes

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [ ]:
print('-' * 55)
df.isnull().sum()

-------------------------------------------------------

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [ ]:
df['category'].unique()

array(['Electronics', 'Accessories', nan], dtype=object)

In [ ]:
df['customer_name'].dropna().unique()

array(['Ramesh Kumar', 'Priya Nair', 'AMIT VERMA', 'Sunita Patel',
       'kiran mehta', 'Deepak Singh', 'Ananya Das', 'Vikram Iyer',
       'Pooja Gupta', 'SURESH RAO', 'Meera Joshi', 'Arjun Nair',
       'Tanvi Mehta', 'Kiran Mehta', 'Rohit Verma', 'Sneha Reddy',
       'Gaurav Shukla', 'Nisha Kapoor', 'Ajay Tiwari', 'ANANYA DAS',
       'Preeti Saxena', 'Amit Bose', 'Rekha Nair', 'Harish Pillai',
       'Sanjay Dubey', 'Kavya Nambiar'], dtype=object)

In [ ]:
df['order_date'].unique()[:6]

array(['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10',
       '07-01-2024', '2024-01-12'], dtype=object)

In [ ]:
df.shape

(30, 9)

In [ ]:
ddf = df.copy()
ddf.shape

(30, 9)

In [ ]:
df.shape

(30, 9)

In [ ]:
len(df)

30

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce', dayfirst=True)
df['order_date'].dt.year

0     2024.0
1     2024.0
2     2024.0
3     2024.0
4     2024.0
5        NaN
6     2024.0
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15    2024.0
16       NaN
17       NaN
18    2024.0
19    2024.0
20    2024.0
21    2024.0
22       NaN
23    2024.0
24    2024.0
25       NaN
26       NaN
27       NaN
28       NaN
29       NaN
Name: order_date, dtype: float64

In [ ]:
df['customer_name'] = (df['customer_name'].str.strip().str.strip())